[{"client_msg_id":"fefefbb3-38d0-4c77-9619-967766afe1d6","type":"message","text":"I'm having some trouble setting a constant variable based on a constant Python object at the module-level.\n\nA MWE:\n```module MyModule\n\nusing PyCall\n\nconst python_code = PyNULL()\n\nfunction __init__()\n    py\"\"\"\n    class Code:\n        def __init__(self, file):\n            # Read code chapters from a JSON file.\n            self.chapters = [\"001-139\", \"140-239\", \"240-279\"] # Mocked\n    \"\"\"\n    copy!(python_code, py\"Code\"(\"somefile.json\"))\nend\n\nfunction get_range(chapterrange)\n    lower, upper = parse.(Int, split(chapterrange, \"-\"))\n    return lower:upper\nend\n\n#const chapter_ranges = get_range.(python_code.chapters)\n\nend # module```\nUncommenting the last line results in an ArgumentError when loading the module (`ArgumentError: ref of NULL PyObject`).\n\nAm I correct that this assignment needs to be done in `__init__` as well? How can I ensure that `chapter_ranges` stays a `const` in that case?","user":"U01CH1E238S","ts":"1613565996.053000","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"XWlS","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"I'm having some trouble setting a constant variable based on a constant Python object at the module-level.\n\nA MWE:\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"module MyModule\n\nusing PyCall\n\nconst python_code = PyNULL()\n\nfunction __init__()\n    py\"\"\"\n    class Code:\n        def __init__(self, file):\n            # Read code chapters from a JSON file.\n            self.chapters = [\"001-139\", \"140-239\", \"240-279\"] # Mocked\n    \"\"\"\n    copy!(python_code, py\"Code\"(\"somefile.json\"))\nend\n\nfunction get_range(chapterrange)\n    lower, upper = parse.(Int, split(chapterrange, \"-\"))\n    return lower:upper\nend\n\n#const chapter_ranges = get_range.(python_code.chapters)\n\nend # module"}]},{"type":"rich_text_section","elements":[{"type":"text","text":"\nUncommenting the last line results in an ArgumentError when loading the module ("},{"type":"text","text":"ArgumentError: ref of NULL PyObject","style":{"code":true}},{"type":"text","text":").\n\nAm I correct that this assignment needs to be done in "},{"type":"text","text":"_","style":{"code":true}},{"type":"text","text":"init","style":{"italic":true,"code":true}},{"type":"text","text":"_","style":{"code":true}},{"type":"text","text":" as well? How can I ensure that "},{"type":"text","text":"chapter_ranges","style":{"code":true}},{"type":"text","text":" stays a "},{"type":"text","text":"const","style":{"code":true}},{"type":"text","text":" in that case?"}]}]}],"thread_ts":"1613565996.053000","reply_count":5,"reply_users_count":3,"latest_reply":"1613567576.054300","reply_users":["B01J9QZ4SP8","U01CH1E238S","UH24GRBLL"],"subscribed":false},{"type":"message","subtype":"bot_message","text":"Can we cross post this publicly to <https://discourse.julialang.org|Discourse> for further visibility? React with :bridge: on the message above to approve. <https://github.com/JuliaCommunity/SlackBridge/blob/main/README.md#faq|More info here>","ts":"1613565998.053100","username":"HelpDeskBot","bot_id":"B01J9QZ4SP8","thread_ts":"1613565996.053000","parent_user_id":"U01CH1E238S"},{"client_msg_id":"d2140f95-ba7d-4fd4-bd9a-43b6803c52ee","type":"message","text":"In the MWE, I expect the following output:\n```julia&gt; using .MyModule\n\njulia&gt; MyModule.chapter_ranges\n3-element Array{UnitRange{Int64},1}:\n 1:139\n 140:239\n 240:279```","user":"U01CH1E238S","ts":"1613566296.053500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"lTjd","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"In the MWE, I expect the following output:\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"julia> using .MyModule\n\njulia> MyModule.chapter_ranges\n3-element Array{UnitRange{Int64},1}:\n 1:139\n 140:239\n 240:279"}]}]}],"thread_ts":"1613565996.053000","parent_user_id":"U01CH1E238S"},{"client_msg_id":"5f7856b7-4c09-4acc-a394-1d957d7acb51","type":"message","text":"you declare `python_code` to be `const` and set it to `PyNULL()` - since you marked it as `const`, the compiler is allowed to inline all accesses to that","user":"UH24GRBLL","ts":"1613566296.053700","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"Ftk","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"you declare "},{"type":"text","text":"python_code","style":{"code":true}},{"type":"text","text":" to be "},{"type":"text","text":"const","style":{"code":true}},{"type":"text","text":" and set it to "},{"type":"text","text":"PyNULL()","style":{"code":true}},{"type":"text","text":" - since you marked it as "},{"type":"text","text":"const","style":{"code":true}},{"type":"text","text":", the compiler is allowed to inline all accesses to that"}]}]}],"thread_ts":"1613565996.053000","parent_user_id":"U01CH1E238S"},{"client_msg_id":"4c6ade65-5085-463f-be83-dc6fb0201272","type":"message","text":"there should be some more information where the `ArgumentError` is thrown - I think it happens in `__init__` when you pass it to `copy!`","user":"UH24GRBLL","ts":"1613566566.053900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"DXS","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"there should be some more information where the "},{"type":"text","text":"ArgumentError","style":{"code":true}},{"type":"text","text":" is thrown - I think it happens in "},{"type":"text","text":"__init__","style":{"code":true}},{"type":"text","text":" when you pass it to "},{"type":"text","text":"copy!","style":{"code":true}}]}]}],"thread_ts":"1613565996.053000","parent_user_id":"U01CH1E238S"},{"client_msg_id":"618e8a73-22b6-49fb-9859-eef45035d27e","type":"message","text":"Sorry for the confusion, the error is thrown when pasting  (or including) the code in the REPL :grimacing:\n```ERROR: ArgumentError: ref of NULL PyObject\nStacktrace:\n [1] _getproperty at /home/elias/.julia/packages/PyCall/tqyST/src/PyCall.jl:299 [inlined]\n [2] __getproperty(::PyCall.PyObject, ::Symbol) at /home/elias/.julia/packages/PyCall/tqyST/src/PyCall.jl:306\n [3] getproperty(::PyCall.PyObject, ::Symbol) at /home/elias/.julia/packages/PyCall/tqyST/src/PyCall.jl:312\n [4] top-level scope at REPL[1]:22```\nI'm not entirely sure how to debug modules that use PyCall.jl.","user":"U01CH1E238S","ts":"1613567576.054300","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"cT/b","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Sorry for the confusion, the error is thrown when pasting  (or including) the code in the REPL "},{"type":"emoji","name":"grimacing"},{"type":"text","text":"\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"ERROR: ArgumentError: ref of NULL PyObject\nStacktrace:\n [1] _getproperty at /home/elias/.julia/packages/PyCall/tqyST/src/PyCall.jl:299 [inlined]\n [2] __getproperty(::PyCall.PyObject, ::Symbol) at /home/elias/.julia/packages/PyCall/tqyST/src/PyCall.jl:306\n [3] getproperty(::PyCall.PyObject, ::Symbol) at /home/elias/.julia/packages/PyCall/tqyST/src/PyCall.jl:312\n [4] top-level scope at REPL[1]:22"}]},{"type":"rich_text_section","elements":[{"type":"text","text":"I'm not entirely sure how to debug modules that use PyCall.jl."}]}]}],"thread_ts":"1613565996.053000","parent_user_id":"U01CH1E238S"}]