[{"client_msg_id":"b19bb22d-d6d3-4d20-95d2-2600d074433d","type":"message","text":"How can I print the otuput of Profile.print() to a file?","user":"UEGRU91B2","ts":"1616453796.425600","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"O7+","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"How can I print the otuput of Profile.print() to a file?"}]}]}],"thread_ts":"1616453796.425600","reply_count":5,"reply_users_count":3,"latest_reply":"1616455007.429900","reply_users":["UEGRU91B2","U6QGE7S86","UCZ7VBGUD"],"is_locked":false,"subscribed":false},{"client_msg_id":"4c86fdcc-3ae4-42a4-b7a5-b49486a1418a","type":"message","text":"Got it\n```f = open(filename, \"w\")\nProfile.print(f)\nclose(f)```","user":"UEGRU91B2","ts":"1616453976.425700","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"E4J","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Got it\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"f = open(filename, \"w\")\nProfile.print(f)\nclose(f)"}]}]}],"thread_ts":"1616453796.425600","parent_user_id":"UEGRU91B2"},{"client_msg_id":"bc206d85-2e9b-4c78-a654-679694600d8a","type":"message","text":"Nice!","user":"U6QGE7S86","ts":"1616454396.425900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"j7aYb","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Nice!"}]}]}],"thread_ts":"1616453796.425600","parent_user_id":"UEGRU91B2"},{"client_msg_id":"28056737-2153-4fca-92f0-976dd78507ae","type":"message","text":"Remember the recommended pattern is to do\n```open(file, \"w\") do f\n    print(f)\nend```","user":"U6QGE7S86","ts":"1616454412.426100","team":"T68168MUP","edited":{"user":"U6QGE7S86","ts":"1616454432.000000"},"blocks":[{"type":"rich_text","block_id":"Gm2pZ","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Remember the recommended pattern is to do\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"open(file, \"w\") do f\n    print(f)\nend"}]}]}],"thread_ts":"1616453796.425600","parent_user_id":"UEGRU91B2"},{"client_msg_id":"4b4300a4-08a4-4a9a-abe5-6431bed41d1f","type":"message","text":"That syntax folds to your same code, but it closes the file should you forget/delete the last `close(f)` and is the \"standard recommended way\"","user":"U6QGE7S86","ts":"1616454475.426400","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"=t5fE","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"That syntax folds to your same code, but it closes the file should you forget/delete the last "},{"type":"text","text":"close(f)","style":{"code":true}},{"type":"text","text":" and is the \"standard recommended way\""}]}]}],"thread_ts":"1616453796.425600","parent_user_id":"UEGRU91B2"},{"client_msg_id":"bc6f0314-f2eb-4f44-a19d-05cc73d04583","type":"message","text":"just to add, the do-block method is\n```function open(f::Function, args...; kwargs...)\n    io = open(args...; kwargs...)\n    try\n        f(io)\n    finally\n        close(io)\n    end\nend```\n(according to `@edit`). What’s useful about that is that the `finally` block gets called even if `f` throws an exception. So that means you always close the file, in contrast to\n```io = open(...)\nf(io)\nclose(io)```\nin which case if `f` throws an error, `close` won’t get called.","user":"UCZ7VBGUD","ts":"1616455007.429900","team":"T68168MUP","edited":{"user":"UCZ7VBGUD","ts":"1616455026.000000"},"blocks":[{"type":"rich_text","block_id":"V+u","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"just to add, the do-block method is\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"function open(f::Function, args...; kwargs...)\n    io = open(args...; kwargs...)\n    try\n        f(io)\n    finally\n        close(io)\n    end\nend"}]},{"type":"rich_text_section","elements":[{"type":"text","text":"(according to `@edit`). What’s useful about that is that the "},{"type":"text","text":"finally","style":{"code":true}},{"type":"text","text":" block gets called even if "},{"type":"text","text":"f","style":{"code":true}},{"type":"text","text":" throws an exception. So that means you always close the file, in contrast to\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"io = open(...)\nf(io)\nclose(io)"}]},{"type":"rich_text_section","elements":[{"type":"text","text":"in which case if "},{"type":"text","text":"f","style":{"code":true}},{"type":"text","text":" throws an error, "},{"type":"text","text":"close","style":{"code":true}},{"type":"text","text":" won’t get called."}]}]}],"thread_ts":"1616453796.425600","parent_user_id":"UEGRU91B2","reactions":[{"name":"100","users":["U6QGE7S86","UEGRU91B2"],"count":2},{"name":"correct_answer","users":["U6QGE7S86"],"count":1}]}]