[{"client_msg_id":"22fc0f24-db2f-40ad-b61a-09737e27c9c4","type":"message","text":"Hallo lads, I am having trouble `using` a package I am developing, perhaps because I deinstalled Python but is required for `SymPy` (?)\n`LoadError: ArgumentError: Path to conda environment is not valid: C:\\Users\\myusername\\.julia\\conda\\3`","user":"U011V84GZ5E","ts":"1616263486.279200","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"ZnjU","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Hallo lads, I am having trouble "},{"type":"text","text":"using ","style":{"code":true}},{"type":"text","text":"a package I am developing, perhaps because I deinstalled Python but is required for "},{"type":"text","text":"SymPy ","style":{"code":true}},{"type":"text","text":"(?)\n"},{"type":"text","text":"LoadError: ArgumentError: Path to conda environment is not valid: C:\\Users\\myusername\\.julia\\conda\\3","style":{"code":true}}]}]}],"thread_ts":"1616263486.279200","reply_count":11,"reply_users_count":5,"latest_reply":"1616271367.284200","reply_users":["U68QW0PUZ","U011V84GZ5E","U0138UTB7A4","U012XER8K4M","U8HHPBKQR"],"is_locked":false,"subscribed":false},{"client_msg_id":"9d2c0f99-b707-47d6-adb1-c18c8601b804","type":"message","text":"You will find it impossible to run Python unless you have Python installed.\nSymPy.jl is a wrapper written in Julia that wraps the Python software \"sympy\".\nTo use the underlying \"sympy\", Julia reaches Python with somethings  for it to do.\nNo Python? Nothing to reach.  Nothing reached? Nothing to be done.","user":"U68QW0PUZ","ts":"1616266331.279900","team":"T68168MUP","edited":{"user":"U68QW0PUZ","ts":"1616266468.000000"},"blocks":[{"type":"rich_text","block_id":"Q+dYF","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"You will find it impossible to run Python unless you have Python installed.\nSymPy.jl is a wrapper written in Julia that wraps the Python software \"sympy\".\nTo use the underlying \"sympy\", Julia reaches Python with somethings  for it to do.\nNo Python? Nothing to reach.  Nothing reached? Nothing to be done."}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"8e1b6f75-49a2-42a7-a990-435a7c619bb9","type":"message","text":"Thanks <@U68QW0PUZ> It puzzles me because I have Python 2.4 actually installed. Could it be it needs Python 3.x or Anaconda?","user":"U011V84GZ5E","ts":"1616266810.280300","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"HKu","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Thanks "},{"type":"user","user_id":"U68QW0PUZ"},{"type":"text","text":" It puzzles me because I have Python 2.4 actually installed. Could it be it needs Python 3.x or Anaconda?"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"c037db76-6b00-45a6-98e8-cec38dc976cf","type":"message","text":"By the way, the word lads is a gendered word to mean male, but there's definitely not just males here but more genders and other people in this community. Just letting you know. I personally like to use \"hello everyone\". Some use \"people\" or \"folks\"","user":"U0138UTB7A4","ts":"1616267846.280500","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"GYb","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"By the way, the word lads is a gendered word to mean male, but there's definitely not just males here but more genders and other people in this community. Just letting you know. I personally like to use \"hello everyone\". Some use \"people\" or \"folks\""}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"f5ac9710-945e-42d7-97ee-db2bea1fa1c6","type":"message","text":"Hmmm not sure what exactly might have gone wrong. I'm not experienced with Julia calling Python. From the error it seems like its looking for a specific conda environment. So maybe it does need Anaconda. My other guess is that maybe Sympy you have actually needs Python 3+ (python 2.4 is pretty old now).","user":"U0138UTB7A4","ts":"1616268039.281300","team":"T68168MUP","edited":{"user":"U0138UTB7A4","ts":"1616268065.000000"},"blocks":[{"type":"rich_text","block_id":"Yth","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Hmmm not sure what exactly might have gone wrong. I'm not experienced with Julia calling Python. From the error it seems like its looking for a specific conda environment. So maybe it does need Anaconda. My other guess is that maybe Sympy you have actually needs Python 3+ (python 2.4 is pretty old now)."}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"23041c89-11d8-4a42-8e93-10760d3a7e4a","type":"message","text":"Thank you <@U0138UTB7A4> for the hint on greetings. I am not a native english speaker","user":"U011V84GZ5E","ts":"1616268724.282400","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"Gup+q","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Thank you "},{"type":"user","user_id":"U0138UTB7A4"},{"type":"text","text":" for the hint on greetings. I am not a native english speaker"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"cd5a70d2-aa62-4a46-a491-c622b0f1225a","type":"message","text":"You're welcome! No worries its ok","user":"U0138UTB7A4","ts":"1616268780.282600","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"2up","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"You're welcome! No worries its ok"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"d5f2008d-284f-4d63-b5b1-25b5f356f0c0","type":"message","text":"2.7 is pretty old. 2.4 is absolutely ancient","user":"U012XER8K4M","ts":"1616270433.282900","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"vJOYx","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"2.7 is pretty old. 2.4 is absolutely ancient"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"41d87385-689d-4fcb-a0b0-2d290b7a4fd8","type":"message","text":"build SymPy probably fixes it","user":"U8HHPBKQR","ts":"1616270963.283200","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"YoK","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"build SymPy probably fixes it"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"ca269058-d9aa-45fe-8e41-dc4128db4e91","type":"message","text":"Julia has to find [an appropriate version of[ Python.  It is not enough for some Python to be somewhere on your machine.\n```using Pkg; Pkg.add(\"Conda\"); Pkg.add(\"SymPy\"); Pkg.build(\"SymPy\"); using SymPy```","user":"U68QW0PUZ","ts":"1616271150.283800","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"v=J","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Julia has to find [an appropriate version of[ Python.  It is not enough for some Python to be somewhere on your machine.\n"}]},{"type":"rich_text_preformatted","elements":[{"type":"text","text":"using Pkg; Pkg.add(\"Conda\"); Pkg.add(\"SymPy\"); Pkg.build(\"SymPy\"); using SymPy"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"9d3b46ab-17d1-45ca-b0a2-fc7c92a978e0","type":"message","text":"you might first `using Pkg. Pkg.remove(\"SymPy\");` just in case","user":"U68QW0PUZ","ts":"1616271185.284000","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"GUv","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"you might first "},{"type":"text","text":"using Pkg. Pkg.remove(\"SymPy\");","style":{"code":true}},{"type":"text","text":" just in case"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"},{"client_msg_id":"eac562eb-fa44-4da3-8bfa-f3fa747c4636","type":"message","text":"Thank you all, I think this solved it. It was an issue with 2.4 vs 3 and the relative path. By the way `Conda.ROOTENV` now returnes its directory","user":"U011V84GZ5E","ts":"1616271367.284200","team":"T68168MUP","blocks":[{"type":"rich_text","block_id":"43fE","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"Thank you all, I think this solved it. It was an issue with 2.4 vs 3 and the relative path. By the way "},{"type":"text","text":"Conda.ROOTENV","style":{"code":true}},{"type":"text","text":" now returnes its directory"}]}]}],"thread_ts":"1616263486.279200","parent_user_id":"U011V84GZ5E"}]